apply plugin: 'com.android.application'

apply plugin: 'com.google.gms.google-services'

apply plugin: 'kotlin-android'


apply plugin: 'com.google.firebase.crashlytics'


repositories {
    maven { url 'https://maven.fabric.io/public' }

    //test attached
    mavenCentral()
    maven {
        url "https://maven.java.net/content/groups/public/"
    }
}

android {
    defaultConfig {
        compileSdk 36
        applicationId "com.sensoguard.hunter"
        minSdkVersion 26
        targetSdkVersion 36
        versionCode 86
        versionName "1.86"
        vectorDrawables.useSupportLibrary = true
    }
    packagingOptions {
        resources {
            pickFirsts += ['META-INF/LICENSE.txt']
        }
    }


    signingConfigs {
        release {
            storeFile file("hunterKeystore.jks")
            storePassword "hunter1234"
            keyAlias "hunteralias"
            keyPassword "hunter1234"
        }
    }

    buildFeatures {
        viewBinding true
    }

    kotlinOptions {
        jvmTarget = '17'
    }


    buildTypes {
        release {
            signingConfig signingConfigs.release
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        debug {
            ext.alwaysUpdateBuildId = false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'

            debuggable true
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    namespace 'com.sensoguard.hunter'
    //compileSdk 34
    //buildToolsVersion '34.0.0'


}



configurations {
    configureEach {
        exclude module: 'commons-logging'
    }
}



dependencies {

    implementation 'androidx.media3:media3-exoplayer:1.7.1'
    implementation 'androidx.media3:media3-ui:1.7.1'
    implementation 'androidx.media3:media3-exoplayer-dash:1.7.1'


    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"

    implementation 'androidx.appcompat:appcompat:1.7.1'//cannot upgrade

    implementation 'androidx.constraintlayout:constraintlayout:2.2.1'

    //implementation 'com.android.support:design:34.0.0'

    implementation 'androidx.lifecycle:lifecycle-extensions:2.2.0'

    //implementation 'com.android.support:support-v4:34.0.0'

    implementation 'androidx.work:work-runtime-ktx:2.10.2'

    testImplementation 'junit:junit:4.13.2'
    implementation 'com.google.android.things:androidthings:1.0'
    implementation 'com.google.android.gms:play-services-maps:19.2.0'
    implementation 'com.github.kai-morich:usb-serial-for-android:1.7.0'
    implementation 'com.google.code.gson:gson:2.13.1'
    implementation 'com.google.android.gms:play-services-location:21.3.0'
    implementation 'com.google.android.material:material:1.12.0'
    implementation 'com.opencsv:opencsv:5.11.2'
    implementation 'com.github.felHR85:UsbSerial:6.0.6'

    //Support language
    implementation 'com.github.delight-im:Android-Languages:v1.0.1'
    implementation files('libs/javax.mail.jar')
    //test attached
    implementation 'com.sun.mail:android-activation:1.6.7'
    //implementation 'ru.egslava:MaskedEditText:1.0.5'
    implementation 'com.squareup.picasso:picasso:2.71828'
    implementation 'com.squareup:android-times-square:1.7.11@aar'
    //glide
    implementation 'com.github.bumptech.glide:glide:4.16.0'
    annotationProcessor 'com.github.bumptech.glide:compiler:4.16.0'


    implementation files('libs/jsoup-1.12.1.jar')

    //firebase
    implementation 'com.google.firebase:firebase-core:21.1.1'
    implementation 'com.google.firebase:firebase-messaging:24.1.2'
    implementation 'com.google.firebase:firebase-analytics:22.5.0'
    implementation 'com.google.firebase:firebase-messaging-directboot:24.1.2'
    implementation 'com.google.firebase:firebase-auth:23.2.1'
    implementation 'com.google.firebase:firebase-crashlytics:19.4.4'


    implementation 'com.google.code.gson:gson:2.13.1'

    //glide
    implementation 'com.github.bumptech.glide:glide:4.16.0'
    annotationProcessor 'com.github.bumptech.glide:compiler:4.16.0'
    implementation 'com.github.bumptech.glide:annotations:4.16.0'

    //retrofit
    implementation 'com.squareup.retrofit2:retrofit:3.0.0'
    implementation 'com.squareup.retrofit2:converter-gson:3.0.0'
    implementation 'com.jakewharton.picasso:picasso2-okhttp3-downloader:1.1.0'


    //azura
    implementation 'com.microsoft.azure:notification-hubs-android-sdk:2.0.0@aar'

    implementation 'androidx.fragment:fragment-ktx:1.8.8'

}
repositories {
    maven {
        url "https://dl.bintray.com/microsoftazuremobile/SDK"
    }

}
